/* Vera · asistente del ERP (demo)
   En el demo el asistente corre en el navegador con reglas sobre los datos del demo: entiende la pregunta,
   el CÓDIGO saca los números (ERP.M) y aquí solo se redactan. En la versión real la redacción y el análisis
   los hace un modelo (Claude / GPT) con las mismas consultas de solo lectura. Nunca inventa: si no está en
   el ERP, lo dice. */
(function () {
  const E = window.ERP, M = E.M, db = E.db;
  const norm = (s) => (s || '').toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[¿?¡!.,;:()"]/g, ' ').replace(/\s+/g, ' ').trim();
  const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
  const hoy = E.HOY, HOY = E.HOY_ISO;
  const MES_RE = /\b(enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|setiembre|octubre|noviembre|diciembre)\b(?:\s+(?:de\s+|del\s+)?(20\d\d))?/;
  const MESES_N = { enero: 1, febrero: 2, marzo: 3, abril: 4, mayo: 5, junio: 6, julio: 7, agosto: 8, septiembre: 9, setiembre: 9, octubre: 10, noviembre: 11, diciembre: 12 };
  const ym = (y, m) => y + '-' + E.pad(m);

  // ---------- extracción ----------
  function periodo(q) {
    const hoyYm = E.mesActual; const [hy, hm] = hoyYm.split('-').map(Number);
    let m = q.match(MES_RE); if (m) { let y = m[2] ? Number(m[2]) : (MESES_N[m[1]] > hm ? hy - 1 : hy); const k = ym(y, MESES_N[m[1]]); const [d, h] = E.rangoMes(k); return { desde: d, hasta: h > HOY ? HOY : h, etiqueta: E.mesLabel(k, true), ym: k, tipo: 'mes' }; }
    if (/\b(hoy)\b/.test(q)) return { desde: HOY, hasta: HOY, etiqueta: 'hoy', tipo: 'dia' };
    if (/\bayer\b/.test(q)) { const d = E.iso(E.addDays(hoy, -1)); return { desde: d, hasta: d, etiqueta: 'ayer', tipo: 'dia' }; }
    if (/esta semana/.test(q)) { const d = E.addDays(hoy, -((hoy.getDay() + 6) % 7)); return { desde: E.iso(d), hasta: HOY, etiqueta: 'esta semana', tipo: 'rango' }; }
    if (/semana pasada/.test(q)) { const fin = E.addDays(hoy, -((hoy.getDay() + 6) % 7) - 1); return { desde: E.iso(E.addDays(fin, -6)), hasta: E.iso(fin), etiqueta: 'la semana pasada', tipo: 'rango' }; }
    if (/mes pasado|mes anterior/.test(q)) { const k = E.mesAnterior(hoyYm, 1); const [d, h] = E.rangoMes(k); return { desde: d, hasta: h, etiqueta: E.mesLabel(k, true), ym: k, tipo: 'mes' }; }
    if (/este mes|el mes|del mes|en el mes/.test(q)) { const [d] = E.rangoMes(hoyYm); return { desde: d, hasta: HOY, etiqueta: E.mesLabel(hoyYm, true) + ' (al día ' + hoy.getDate() + ')', ym: hoyYm, tipo: 'mes' }; }
    if (/trimestre|3 meses|tres meses/.test(q)) return { desde: E.iso(E.addDays(hoy, -90)), hasta: HOY, etiqueta: 'los últimos 90 días', tipo: 'rango' };
    if (/6 meses|seis meses|semestre/.test(q)) return { desde: E.iso(E.addDays(hoy, -182)), hasta: HOY, etiqueta: 'los últimos 6 meses', tipo: 'rango' };
    if (/ano pasado|2025/.test(q)) return { desde: '2025-01-01', hasta: '2025-12-31', etiqueta: '2025', tipo: 'anio' };
    if (/este ano|en el ano|del ano|acumulado|ytd|2026/.test(q)) return { desde: '2026-01-01', hasta: HOY, etiqueta: '2026 (enero a hoy)', tipo: 'anio' };
    if (/12 meses|ultimo ano|doce meses/.test(q)) return { desde: E.iso(E.addDays(hoy, -365)), hasta: HOY, etiqueta: 'los últimos 12 meses', tipo: 'rango' };
    return null;
  }
  function sucursal(q) { const t = [['s1', /\bnorte\b|monterrey/], ['s2', /\bcentro\b|cdmx|ciudad de mexico/], ['s3', /\bsur\b|puebla/], ['s4', /\boriente\b|veracruz/]]; for (const [id, re] of t) if (re.test(q)) return id; return null; }
  function linea(q) { const t = [['l1', /herramienta/], ['l2', /electric/], ['l3', /plomer/], ['l4', /pintura|acabado/], ['l5', /construccion|cemento y|materiales de construccion/], ['l6', /seguridad/]]; for (const [id, re] of t) if (re.test(q)) return id; return null; }
  function producto(q) { let best = null, bs = 0; db.productos.forEach(p => { const toks = norm(p.nombre).split(' ').filter(t => t.length > 3 && !/^\d/.test(t)); let sc = 0; toks.forEach(t => { if (q.includes(t)) sc += t.length; }); if (sc > bs) { bs = sc; best = p; } }); return bs >= 6 ? best : null; }
  function cliente(q) { let best = null, bs = 0; db.clientes.forEach(c => { const toks = norm(c.nombre).split(' ').filter(t => t.length > 3 && !['s.a.', 'de', 'c.v.', 'de', 'r.l.', 'grupo', 'norte', 'sur', 'centro', 'plus', 'express', 'industrial'].includes(t)); let sc = 0; toks.forEach(t => { if (q.includes(t)) sc += t.length; }); if (sc > bs) { bs = sc; best = c; } }); return bs >= 9 ? best : null; }
  function vendedor(q) { return db.vendedores.find(v => { const n = norm(v.nombre).split(' '); return q.includes(norm(v.nombre)) || (n[0].length > 3 && new RegExp('\\b' + n[0] + '\\b').test(q) && new RegExp('\\b' + n[1] + '\\b').test(q)) || (n[0].length > 4 && new RegExp('\\b' + n[0] + '\\b').test(q)); }) || null; }
  function proveedor(q) { let best = null, bs = 0; db.proveedores.forEach(v => { const toks = norm(v.nombre).split(' ').filter(t => t.length > 4 && !['s.a.', 'c.v.', 'distribucion', 'nacional', 'industrial', 'mayoreo'].includes(t)); let sc = 0; toks.forEach(t => { if (q.includes(t)) sc += t.length; }); if (sc > bs) { bs = sc; best = v; } }); return bs >= 8 ? best : null; }
  function dimension(q) { if (/por sucursal|sucursales|por plaza/.test(q)) return 'sucursal'; if (/por linea|lineas|familia/.test(q)) return 'linea'; if (/por producto|productos/.test(q)) return 'producto'; if (/por cliente|clientes/.test(q)) return 'cliente'; if (/por vendedor|vendedores/.test(q)) return 'vendedor'; return null; }
  function topN(q) { const m = q.match(/\b(?:top|mejores|peores|primeros|principales)\s*(\d{1,2})|\b(\d{1,2})\s+(?:mejores|peores|principales|primeros)/); return m ? Number(m[1] || m[2]) : 5; }
  const esPeor = (q) => /peor|menos vend|mas bajo|caen|bajan|bajaron/.test(q);

  // ---------- formato ----------
  const $ = E.corto, P = E.pct, $$ = E.money0;
  const signo = (x) => x == null ? '—' : (x >= 0 ? '+' : '−') + P(Math.abs(x));
  const li = (arr) => '<ul>' + arr.map(x => '<li>' + x + '</li>').join('') + '</ul>';
  const tabla = (cols, filas) => ({ cols, filas });
  const fuente = (t, def) => ({ fuente: 'ERP · ' + t, definicion: def || null });
  const nombreSuc = (id) => id ? E.nombreDe.suc(id) : 'todas las sucursales';
  const ahora = () => hoy.getHours() + ':' + E.pad(hoy.getMinutes());

  // ---------- respuestas ----------
  function rComparativo(f, per, dim, q) {
    const k = per && per.ym ? per.ym : E.mesActual; const filtro = { sucursal: f.sucursal, linea: f.linea, producto: f.producto, cliente: f.cliente, vendedor: f.vendedor };
    let texto, grafica, tab, sug = [];
    if (per && per.tipo !== 'mes') {
      const r = M.resumen(M.filtrarLineas(Object.assign({ desde: per.desde, hasta: per.hasta }, filtro)));
      const dias = E.diasEntre(per.desde, per.hasta) + 1; const prevD = E.iso(E.addDays(E.parse(per.desde), -dias)), prevH = E.iso(E.addDays(E.parse(per.desde), -1));
      const r0 = M.resumen(M.filtrarLineas(Object.assign({ desde: prevD, hasta: prevH }, filtro)));
      texto = `${cap(per.etiqueta)} en ${nombreSuc(f.sucursal)}${f.linea ? ', línea ' + E.nombreDe.lin(f.linea) : ''}: <b>${$(r.venta)}</b> de venta neta en ${E.num.format(r.facturas)} facturas (ticket ${$(r.ticket)}). Contra el periodo anterior de la misma duración: <b>${signo(r0.venta ? r.venta / r0.venta - 1 : null)}</b>.`;
    } else {
      const c = M.comparativo(k, filtro); const parcial = k === E.mesActual; let varAnual = c.varAnual, lyTxt = E.mesLabel(E.mesAnterior(k, 12), true); if (parcial) { const d0 = E.rangoMes(E.mesAnterior(k, 12))[0]; const ly = M.resumen(M.filtrarLineas(Object.assign({}, filtro, { desde: d0, hasta: E.iso(E.addDays(E.parse(d0), hoy.getDate() - 1)) }))); varAnual = ly.venta ? c.actual.venta / ly.venta - 1 : null; lyTxt = 'los mismos días de ' + lyTxt; }
      texto = `${cap(E.mesLabel(k, true))}${parcial ? ' (al día ' + hoy.getDate() + ')' : ''} en ${nombreSuc(f.sucursal)}${f.linea ? ', línea ' + E.nombreDe.lin(f.linea) : ''}${f.vendedor ? ', vendedor ' + E.nombreDe.vend(f.vendedor) : ''}: <b>${$(c.actual.venta)}</b> de venta neta, <b>${signo(varAnual)}</b> contra ${lyTxt}${parcial ? '' : ''} y ${signo(c.varMensual)} contra ${E.mesLabel(E.mesAnterior(k, 1))}${parcial ? ' completo' : ''}. ${E.num.format(c.actual.facturas)} facturas, ticket promedio ${$(c.actual.ticket)}.`;
      if (parcial) texto += ` Al ritmo actual, el mes cerraría en <b>${$(c.actual.venta / hoy.getDate() * 30)}</b>.`;
      if (!dim && !f.sucursal) dim = 'sucursal';
    }
    const meses = M.porMes(Object.assign({ desde: E.rangoMes(E.mesAnterior(k, 12))[0], hasta: E.rangoMes(k)[1] }, filtro));
    grafica = { tipo: 'bar', titulo: 'Venta neta por mes', labels: meses.map(m => E.mesLabel(m.mes)), series: [{ label: 'Venta neta', data: meses.map(m => Math.round(m.venta)) }] };
    if (dim) {
      const rango = per && per.tipo !== 'mes' ? { desde: per.desde, hasta: per.hasta } : { desde: E.rangoMes(k)[0], hasta: E.rangoMes(k)[1] };
      const rows = M.por(dim, Object.assign({}, filtro, rango)); const prev = M.por(dim, Object.assign({}, filtro, { desde: E.rangoMes(E.mesAnterior(k, 12))[0], hasta: E.rangoMes(E.mesAnterior(k, 12))[1] }));
      const n = topN(q); const lista = (esPeor(q) ? rows.slice().reverse() : rows).slice(0, dim === 'sucursal' || dim === 'linea' ? 6 : n);
      tab = tabla(['#', cap(dim), 'Venta neta', 'Vs. año ant.', 'Facturas'], lista.map((r, i) => { const p0 = prev.find(x => x.id === r.id); return [i + 1, r.nombre, $$(r.venta), p0 && p0.venta ? signo(r.venta / p0.venta - 1) : '—', E.num.format(r.facturas)]; }));
      if (/top|mejores|peores|principales|primeros/.test(q) && (dim === 'cliente' || dim === 'producto' || dim === 'vendedor')) { const tot = rows.reduce((a, r) => a + r.venta, 0), sum = lista.reduce((a, r) => a + r.venta, 0); texto = `${esPeor(q) ? 'Los ' + lista.length + ' ' + dim + 's con menos venta' : 'Top ' + lista.length + ' ' + dim + 's'} de ${per ? per.etiqueta : E.mesLabel(k, true)}${f.sucursal ? ' en ' + nombreSuc(f.sucursal) : ''}: ${lista.slice(0, 3).map((r, i) => (i + 1) + ') ' + r.nombre.split(',')[0] + ' ' + $(r.venta)).join(', ')}… Entre los ${lista.length} suman <b>${$(sum)}</b>, ${P(sum / tot, 0)} de la venta del periodo (${$(tot)}).`; }
      if (dim === 'sucursal' && rows.length > 1) { const baja = rows.filter(r => { const p0 = prev.find(x => x.id === r.id); return p0 && p0.venta && r.venta < p0.venta; }); if (baja.length) texto += ` <b>${baja.map(b => b.nombre).join(' y ')}</b> ${baja.length > 1 ? 'bajan' : 'baja'} contra el año pasado; ${rows.length - baja.length === 3 ? 'las otras tres crecen' : 'el resto crece'}.`; else texto += ' Todas las sucursales crecen contra el año pasado.'; }
      if (dim === 'sucursal' && !f.sucursal) { const pp = M.precioPromedio({ sucursal: 's4' }); const u = pp[pp.length - 1], h6 = pp[Math.max(0, pp.length - 7)]; if (u && h6 && u.indice / h6.indice - 1 < -0.015) texto += ` Lo que me preocupa de Oriente: su <b>precio promedio va a la baja</b> (${signo(u.indice / h6.indice - 1)} en seis meses, deflactado); vende menos y más barato.`; }
      sug = ['¿Y el margen?', '¿Qué clientes dejaron de comprar?', 'Muéstrame por línea', '¿Cómo va septiembre?'];
    } else sug = ['Desglósalo por sucursal', 'Por línea de producto', '¿Y el margen?', 'Top 10 clientes de ' + (per ? per.etiqueta : 'agosto')];
    const acc = [{ label: 'Ver facturas', tipo: 'ir', vista: 'ventas-facturas', filtro: k }, { label: 'Abrir informe de ventas', tipo: 'ir', vista: 'informes', filtro: 'ventas' }];
    return Object.assign({ texto, grafica, tabla: tab, sugerencias: sug, acciones: acc }, fuente('facturas y líneas de factura', 'Venta neta'));
  }
  function rMargen(f, per, dim, q, ctx) {
    if (!puede(ctx, 'margen')) return candado('el margen y la utilidad');
    const k = per && per.ym ? per.ym : E.mesActual; const rango = per && per.tipo !== 'mes' ? { desde: per.desde, hasta: per.hasta } : { desde: E.rangoMes(k)[0], hasta: E.rangoMes(k)[1] };
    const filtro = Object.assign({ sucursal: f.sucursal, linea: f.linea, producto: f.producto, cliente: f.cliente, vendedor: f.vendedor }, rango);
    const r = M.resumen(M.filtrarLineas(filtro)); const prev = M.resumen(M.filtrarLineas(Object.assign({}, filtro, { desde: E.rangoMes(E.mesAnterior(k, 12))[0], hasta: E.rangoMes(E.mesAnterior(k, 12))[1] })));
    let texto = `Margen bruto de ${per ? per.etiqueta : E.mesLabel(k, true)} en ${nombreSuc(f.sucursal)}: <b>${$(r.margen)}</b>, es decir <b>${P(r.margenPct)}</b> de la venta neta (${$(r.venta)}). El año pasado en el mismo periodo fue ${P(prev.margenPct)}${r.margenPct != null && prev.margenPct != null ? (r.margenPct < prev.margenPct ? ', así que <b>perdimos ' + ((prev.margenPct - r.margenPct) * 100).toFixed(1) + ' puntos</b>' : ', ' + ((r.margenPct - prev.margenPct) * 100).toFixed(1) + ' puntos más') : ''}.`;
    dim = dim || 'linea'; const rows = M.por(dim, filtro).sort((a, b) => (a.margenPct || 0) - (b.margenPct || 0));
    const tab = tabla([cap(dim), 'Venta neta', 'Margen', '% margen'], rows.slice(0, 8).map(x => [x.nombre, $$(x.venta), $$(x.margen), P(x.margenPct)]));
    const neg = M.margenNegativo(Object.assign({}, filtro, { desde: rango.desde }));
    if (neg.length) texto += ` Lo que no cuadra: <b>${neg.length} producto${neg.length > 1 ? 's se venden' : ' se vende'} por debajo del costo</b> (${neg.slice(0, 2).map(n => n.nombre + ' en ' + n.sucursalNombre + ', ' + P(n.margenPct)).join('; ')}); la pérdida acumulada es ${$(neg.reduce((a, n) => a + n.perdida, 0))}. El costo subió con el proveedor y el precio de lista no se actualizó.`;
    const grafica = { tipo: 'bar', titulo: '% de margen por ' + dim, labels: rows.map(x => x.nombre), series: [{ label: '% margen', data: rows.map(x => Math.round((x.margenPct || 0) * 1000) / 10) }] };
    return Object.assign({ texto, tabla: tab, grafica, sugerencias: ['¿Qué productos se venden bajo costo?', 'Margen por sucursal', '¿Cómo cerró agosto?'], acciones: neg.length ? [{ label: 'Actualizar precio de ' + neg[0].nombre, tipo: 'precio', producto: neg[0].producto }, { label: 'Ver productos con margen negativo', tipo: 'ir', vista: 'inventario-productos', filtro: 'margen' }] : [] }, fuente('líneas de factura y costos', 'Margen bruto'));
  }
  function rInactivos(f) {
    const lista = M.clientesInactivos(60).filter(c => !f.sucursal || c.sucursal === f.sucursal); const rel = lista.filter(c => c.tamano !== 'chico');
    if (!lista.length) return Object.assign({ texto: 'No hay clientes que compraran en los 12 meses previos y lleven más de 60 días sin factura' + (f.sucursal ? ' en ' + nombreSuc(f.sucursal) : '') + '.', sugerencias: ['¿Cómo va el mes?', '¿Quién me debe?'] }, fuente('facturas y clientes', 'Cliente inactivo'));
    const total = rel.reduce((a, c) => a + c.venta12, 0);
    const texto = `${rel.length} cliente${rel.length > 1 ? 's' : ''} grande${rel.length > 1 ? 's' : ''} o mediano${rel.length > 1 ? 's' : ''} ${f.sucursal ? 'de ' + nombreSuc(f.sucursal) + ' ' : ''}dej${rel.length > 1 ? 'aron' : 'ó'} de comprar: <b>${$(total)} al año</b> que ya no están entrando. ${[...new Set(rel.map(c => E.nombreDe.suc(c.sucursal)))].join(', ')}. ${rel.every(c => c.sucursal === 's4') ? 'Los tres son de Oriente y del mismo vendedor (' + E.nombreDe.vend(rel[0].vendedor) + '); su última compra fue a finales de junio, casi el mismo día. Eso no parece casualidad: ' : ''}¿Preparo el mensaje para ${rel.length && rel.every(c => c.vendedor === rel[0].vendedor) ? E.nombreDe.vend(rel[0].vendedor).split(' ')[0] : 'los vendedores'}?` + (lista.length > rel.length ? ` También hay ${lista.length - rel.length} clientes chicos en la misma situación.` : '');
    const tab = tabla(['Cliente', 'Sucursal', 'Vendedor', 'Última compra', 'Días', 'Compró en 12 m'], lista.slice(0, 8).map(c => [c.nombre, E.nombreDe.suc(c.sucursal), E.nombreDe.vend(c.vendedor), E.fechaCorta(c.ultima), c.dias, $$(c.venta12)]));
    return Object.assign({ texto, tabla: tab, sugerencias: ['Sí, prepara el mensaje para el vendedor', '¿Cuánto vendía Oriente antes?', 'Recuérdame revisarlo el viernes'], acciones: [{ label: 'Preparar mensaje al vendedor', tipo: 'pregunta', texto: 'Prepara el mensaje para el vendedor de Oriente' }, { label: 'Ver clientes inactivos', tipo: 'ir', vista: 'ventas-clientes', filtro: 'inactivos' }], contexto: { inactivos: rel } }, fuente('facturas y clientes', 'Cliente inactivo'));
  }
  function rCartera(f, q) {
    const c = M.cartera({ sucursal: f.sucursal, cliente: f.cliente, vendedor: f.vendedor }); const t = c.tramos;
    if (f.cliente) { const cl = E.idx.cli[f.cliente]; const vs = c.vencidas; return Object.assign({ texto: vs.length ? `${cl.nombre} debe <b>${$(c.totalVencido)}</b> vencidos en ${vs.length} factura${vs.length > 1 ? 's' : ''}; la más vieja lleva ${vs[0].dias} días (${vs[0].id}, ${$$(vs[0].saldo)}). Además tiene ${$(c.porVencer)} por vencer. Su crédito es a ${cl.credito} días y su perfil de pago histórico es «${cl.perfil}».` : `${cl.nombre} no tiene saldo vencido. Tiene ${$(c.porVencer)} por vencer dentro de su crédito a ${cl.credito} días.`, tabla: vs.length ? tabla(['Factura', 'Fecha', 'Venció', 'Días', 'Saldo'], vs.slice(0, 8).map(v => [v.id, E.fechaCorta(v.fecha), E.fechaCorta(v.vence), v.dias, $$(v.saldo)])) : null, sugerencias: ['Redacta el recordatorio de pago', '¿Cuánto me compró este año?'], acciones: vs.length ? [{ label: 'Redactar recordatorio', tipo: 'pregunta', texto: 'Redacta el recordatorio de pago para ' + cl.nombre }, { label: 'Ver en Cobranza', tipo: 'ir', vista: 'finanzas-cobranza', filtro: cl.id }] : [] }, fuente('facturas y pagos', 'Cartera vencida')); }
    const umbral = /90/.test(q) ? 90 : /60/.test(q) ? 60 : /30/.test(q) ? 30 : 0; const pc = umbral ? c.porCliente.filter(x => x.maxDias > umbral) : c.porCliente;
    if (umbral) { const texto = pc.length ? `Con más de ${umbral} días vencidos hay <b>${pc.length} cliente${pc.length > 1 ? 's' : ''}</b> por <b>${$(pc.reduce((a, x) => a + x.saldo, 0))}</b> de saldo vencido total: ${pc.slice(0, 3).map(x => x.nombre.split(',')[0] + ' (' + $(x.saldo) + ', ' + x.maxDias + ' días, ' + E.nombreDe.vend(x.vendedor).split(' ')[0] + ')').join('; ')}. Del total vencido de la empresa (${$(c.totalVencido)}), lo de más de 90 días es ${$(t['>90'])}.` : `Nadie debe más de ${umbral} días. La cartera vencida total es ${$(c.totalVencido)}, casi toda de 1 a 30 días.`; return Object.assign({ texto, tabla: pc.length ? tabla(['Cliente', 'Sucursal', 'Vendedor', 'Facturas', 'Máx. días', 'Saldo vencido'], pc.slice(0, 10).map(x => [x.nombre, E.nombreDe.suc(x.sucursal), E.nombreDe.vend(x.vendedor), x.facturas, x.maxDias, $$(x.saldo)])) : null, sugerencias: ['Redacta el recordatorio para los vencidos a más de ' + umbral + ' días', '¿Cómo va la cobranza en general?'], acciones: pc.length ? [{ label: 'Redactar recordatorios', tipo: 'pregunta', texto: 'Redacta el recordatorio para los clientes vencidos a más de ' + umbral + ' días' }, { label: 'Ver Cobranza', tipo: 'ir', vista: 'finanzas-cobranza', filtro: '>' + umbral }] : [] }, fuente('facturas y pagos', 'Cartera vencida')); }
    const texto = `Cartera vencida${f.sucursal ? ' de ' + nombreSuc(f.sucursal) : ''}: <b>${$(c.totalVencido)}</b> en ${c.vencidas.length} facturas de ${c.porCliente.length} clientes. Por antigüedad: ${$(t['1-30'])} de 1 a 30 días, ${$(t['31-60'])} de 31 a 60, ${$(t['61-90'])} de 61 a 90 y <b>${$(t['>90'])} a más de 90 días</b>. Además hay ${$(c.porVencer)} por vencer. ${c.porCliente.length ? 'Los tres que más deben: ' + c.porCliente.slice(0, 3).map(x => x.nombre + ' (' + $(x.saldo) + ', ' + x.maxDias + ' días)').join('; ') + '.' : ''}`;
    const tab = tabla(['Cliente', 'Sucursal', 'Vendedor', 'Facturas', 'Máx. días', 'Saldo vencido'], c.porCliente.slice(0, topN(q) > 5 ? topN(q) : 8).map(x => [x.nombre, E.nombreDe.suc(x.sucursal), E.nombreDe.vend(x.vendedor), x.facturas, x.maxDias, $$(x.saldo)]));
    const grafica = { tipo: 'bar', titulo: 'Saldo vencido por antigüedad', labels: ['1–30', '31–60', '61–90', '> 90'], series: [{ label: 'Saldo', data: [t['1-30'], t['31-60'], t['61-90'], t['>90']].map(Math.round) }] };
    return Object.assign({ texto, tabla: tab, grafica, sugerencias: ['Redacta el recordatorio para los vencidos a más de 60 días', '¿Quién debe más de 90 días?', '¿Cómo va la cobranza de Norte?'], acciones: [{ label: 'Redactar recordatorios', tipo: 'pregunta', texto: 'Redacta el recordatorio para los clientes vencidos' }, { label: 'Ver Cobranza', tipo: 'ir', vista: 'finanzas-cobranza' }] }, fuente('facturas y pagos', 'Cartera vencida'));
  }
  function rDuplicadas() {
    const d = M.duplicadasProveedor(); if (!d.length) return Object.assign({ texto: 'No encuentro facturas de proveedor duplicadas (mismo proveedor, mismo folio y mismo total).', sugerencias: ['Revisa las compras del trimestre'] }, fuente('facturas de proveedor', 'Factura de proveedor duplicada'));
    const total = d.reduce((a, x) => a + x.total, 0); const pag = d.filter(x => x.pagadaDosVeces);
    const texto = `Encontré <b>${d.length} facturas de proveedor capturadas dos veces</b> por <b>${$(total)}</b>, de ${[...new Set(d.map(x => x.nombre))].length} proveedores de servicios (${[...new Set(d.map(x => x.nombre.split(',')[0]))].join(', ')}). ${pag.length ? '<b>' + pag.length + ' ya se pagaron dos veces</b> (' + $(pag.reduce((a, x) => a + x.total, 0)) + ' a recuperar); ' : ''}las demás siguen por pagar y se pueden cancelar hoy antes de que salga el pago. Propongo empezar por ahí: es dinero recuperable esta semana.`;
    const tab = tabla(['Proveedor', 'Folio', 'Fechas', 'Total', 'Estado'], d.map(x => [x.nombre.split(',')[0], x.folioProv, x.fechas.map(E.fechaCorta).join(' y '), $$(x.total), x.pagadaDosVeces ? 'pagada 2 veces' : x.estados.join(' / ')]));
    return Object.assign({ texto, tabla: tab, sugerencias: ['Cancela las que siguen por pagar', 'Prepara el mensaje para Compras', 'Recuérdame revisar las pagadas el lunes'], acciones: [{ label: 'Ver y cancelar duplicadas', tipo: 'ir', vista: 'compras-facturas', filtro: 'duplicadas' }, { label: 'Encargo: dar seguimiento con Compras', tipo: 'encargo', texto: 'Dar seguimiento con Compras a las ' + d.length + ' facturas duplicadas (' + $(total) + ')' }] }, fuente('facturas de proveedor y pagos', 'Factura de proveedor duplicada'));
  }
  function rCompras(f, per, q) {
    const aum = M.aumentosProveedor(); const dup = M.duplicadasProveedor(); const muerto = M.inventarioMuerto(120); const cxp = M.cuentasPorPagar();
    const rango = per ? { desde: per.desde, hasta: per.hasta } : { desde: E.iso(E.addDays(hoy, -90)), hasta: HOY };
    const prov = M.comprasPorProveedor(rango); const total = prov.reduce((a, p) => a + p.compras, 0);
    if (f.proveedor) { const v = E.idx.prov[f.proveedor]; const meses = M.comprasPorMes({ proveedor: v.id }).slice(-12); const a = aum.find(x => x.proveedor === v.id); const fp = db.facturasProv.filter(x => x.proveedor === v.id && x.estado !== 'pagada'); return Object.assign({ texto: `${v.nombre}: compras de ${$(meses.reduce((s, m) => s + m.compras, 0))} en los últimos 12 meses, línea ${E.nombreDe.lin(v.linea)}, crédito a ${v.credito} días. ${a ? '<b>Subió sus precios ' + P(a.variacion, 0) + '</b> en el último trimestre contra el anterior, sin una renegociación registrada. ' : 'Sus precios se mantienen dentro del índice de costos. '}${fp.length ? 'Tiene ' + fp.length + ' factura' + (fp.length > 1 ? 's' : '') + ' por pagar por ' + $(fp.reduce((s, x) => s + x.total, 0)) + '.' : 'No tiene facturas por pagar.'}`, grafica: { tipo: 'line', titulo: 'Compras por mes', labels: meses.map(m => E.mesLabel(m.mes)), series: [{ label: 'Compras', data: meses.map(m => Math.round(m.compras)) }] }, sugerencias: a ? ['Prepara el mensaje al proveedor', '¿Qué otro proveedor vende lo mismo?'] : ['Compras por proveedor del trimestre'], acciones: [{ label: 'Ver proveedor', tipo: 'ir', vista: 'compras-proveedores', filtro: v.id }].concat(a ? [{ label: 'Redactar mensaje al proveedor', tipo: 'pregunta', texto: 'Prepara el mensaje para ' + v.nombre.split(',')[0] + ' por el aumento' }] : []) }, fuente('órdenes de compra y facturas de proveedor')); }
    let texto = `Compras de ${per ? per.etiqueta : 'los últimos 90 días'}: <b>${$(total)}</b> con ${prov.length} proveedores. Revisé el trimestre y encontré tres cosas:`;
    const puntos = [];
    if (aum.length) puntos.push(`<b>${aum[0].nombre.split(',')[0]} subió ${P(aum[0].variacion, 0)}</b> sin renegociación registrada (${$(aum[0].compras90)} comprados en el trimestre).`);
    if (dup.length) puntos.push(`<b>${dup.length} facturas duplicadas</b> por ${$(dup.reduce((a, x) => a + x.total, 0))}; ${dup.filter(x => x.pagadaDosVeces).length} ya pagadas dos veces.`);
    if (muerto.length) puntos.push(`<b>${muerto.length} productos con más de 120 días de inventario</b> (${muerto.map(m => m.nombre + ' en ' + m.sucursalNombre + ', ' + (m.dias === null ? 'sin venta' : m.dias + ' días')).join('; ')}), ${$(muerto.reduce((a, m) => a + m.valor, 0))} parados: no conviene recomprar.`);
    puntos.push(`Por pagar: ${$(cxp.total)}, de los cuales ${$(cxp.proximas15)} vencen en 15 días y ${$(cxp.vencidas)} ya están vencidos.`);
    texto += li(puntos) + 'Propongo empezar por las duplicadas: dinero recuperable esta semana. Te dejo la lista.';
    const tab = tabla(['Proveedor', 'Línea', 'Compras'], prov.slice(0, 8).map(p => [p.nombre.split(',')[0], p.linea, $$(p.compras)]));
    return Object.assign({ texto, tabla: tab, sugerencias: ['Muéstrame las duplicadas', '¿Qué proveedor subió precios?', 'Compras por mes'], acciones: [{ label: 'Ver duplicadas', tipo: 'ir', vista: 'compras-facturas', filtro: 'duplicadas' }, { label: 'Ver órdenes de compra', tipo: 'ir', vista: 'compras-ordenes' }] }, fuente('órdenes de compra, facturas de proveedor, pagos y existencias'));
  }
  function rInventario(f, q) {
    if (/muerto|sin rotacion|parado|sin movimiento|dias de inventario|no se vende|no rota/.test(q)) { const m = M.inventarioMuerto(120).filter(x => !f.sucursal || x.sucursal === f.sucursal); return Object.assign({ texto: m.length ? `${m.length} producto${m.length > 1 ? 's' : ''} con más de 120 días de inventario${f.sucursal ? ' en ' + nombreSuc(f.sucursal) : ''}: <b>${$(m.reduce((a, x) => a + x.valor, 0))} parados</b> a costo. ${m.map(x => x.nombre + ' en ' + x.sucursalNombre + ' (' + x.existencia + ' ' + E.idx.prod[x.producto].unidad + ', ' + (x.dias === null ? 'sin venta en 90 días' : x.dias + ' días') + ')').join('; ')}. Propongo traspasar a la sucursal que sí lo vende o promocionarlo; y no recomprar.` : 'No hay productos con más de 120 días de inventario.', tabla: m.length ? tabla(['Producto', 'Sucursal', 'Existencia', 'Venta diaria', 'Días', 'Valor a costo'], m.map(x => [x.nombre, x.sucursalNombre, x.existencia, x.ventaDiaria, x.dias === null ? 'sin venta' : x.dias, $$(x.valor)])) : null, sugerencias: ['¿Dónde sí se vende la escalera?', '¿Qué está bajo mínimo?', 'Vigila estos productos'], acciones: [{ label: 'Ver existencias sin rotación', tipo: 'ir', vista: 'inventario-existencias', filtro: 'muerto' }, { label: 'Encargo: vigilar inventario parado', tipo: 'encargo', texto: 'Vigilar los productos con más de 120 días de inventario y avisar si cambian' }] }, fuente('existencias y líneas de factura', 'Días de inventario')); }
    if (/minimo|falta|reordenar|agotad|se acaba|surtir|comprar/.test(q)) { const b = M.bajoMinimo().filter(x => !f.sucursal || x.sucursal === f.sucursal); return Object.assign({ texto: `${b.length} producto${b.length !== 1 ? 's' : ''} bajo mínimo${f.sucursal ? ' en ' + nombreSuc(f.sucursal) : ''}. Los más urgentes (menos días de existencia): ${b.slice(0, 4).map(x => x.nombre + ' en ' + x.sucursalNombre + ' (' + (x.dias === null ? 'sin venta' : x.dias + ' días') + ')').join('; ')}. Puedo preparar las órdenes de compra agrupadas por proveedor.`, tabla: tabla(['Producto', 'Sucursal', 'Existencia', 'Mínimo', 'Venta diaria', 'Días'], b.slice(0, 10).map(x => [x.nombre, x.sucursalNombre, x.existencia, x.minimo, x.ventaDiaria, x.dias === null ? '—' : x.dias])), sugerencias: ['Prepara las órdenes de compra', '¿Qué está parado en inventario?'], acciones: [{ label: 'Ver bajo mínimo', tipo: 'ir', vista: 'inventario-existencias', filtro: 'minimo' }, { label: 'Nueva orden de compra', tipo: 'ir', vista: 'compras-ordenes', filtro: 'nueva' }] }, fuente('existencias y líneas de factura', 'Días de inventario')); }
    if (f.producto) { const p = f.producto; const ex = db.existencias.filter(e => e.producto === p.id); const tot = ex.reduce((a, e) => a + e.existencia, 0); const v90 = M.resumen(M.filtrarLineas({ producto: p.id, desde: E.iso(E.addDays(hoy, -90)) })); return Object.assign({ texto: `${p.nombre} (${p.sku}): <b>${E.num.format(tot)} ${p.unidad}</b> en total. ${ex.map(e => E.nombreDe.suc(e.sucursal) + ' ' + e.existencia + (e.dias === null ? ' (sin venta)' : ' (' + e.dias + ' días)')).join(' · ')}. En 90 días se vendieron ${E.num.format(v90.unidades)} ${p.unidad} por ${$(v90.venta)} con ${P(v90.margenPct)} de margen. Precio de lista ${E.money(p.precio)}, costo ${E.money(p.costo)}.`, tabla: tabla(['Sucursal', 'Existencia', 'Mínimo', 'Venta diaria', 'Días'], ex.map(e => [E.nombreDe.suc(e.sucursal), e.existencia, e.minimo, e.ventaDiaria, e.dias === null ? '—' : e.dias])), sugerencias: ['¿Cuánto vendimos de ' + p.nombre.split(' ')[0].toLowerCase() + ' este año?', '¿Quién nos lo surte?'], acciones: [{ label: 'Ver producto', tipo: 'ir', vista: 'inventario-productos', filtro: p.id }] }, fuente('existencias, líneas de factura y catálogo')); }
    const ex = db.existencias.filter(e => !f.sucursal || e.sucursal === f.sucursal); const valor = ex.reduce((a, e) => a + e.existencia * E.idx.prod[e.producto].costo, 0); const conDias = ex.filter(e => e.dias !== null); const prom = conDias.reduce((a, e) => a + e.dias * e.existencia * E.idx.prod[e.producto].costo, 0) / (valor || 1); const bajo = M.bajoMinimo().filter(x => !f.sucursal || x.sucursal === f.sucursal).length; const muerto = M.inventarioMuerto(120).filter(x => !f.sucursal || x.sucursal === f.sucursal);
    const porSuc = db.sucursales.map(s => ({ nombre: s.nombre, valor: ex.filter(e => e.sucursal === s.id).reduce((a, e) => a + e.existencia * E.idx.prod[e.producto].costo, 0) }));
    return Object.assign({ texto: `Inventario${f.sucursal ? ' de ' + nombreSuc(f.sucursal) : ''}: <b>${$(valor)}</b> a costo, con <b>${Math.round(prom)} días</b> de inventario promedio (ponderado por valor). ${bajo} productos bajo mínimo y ${muerto.length} con más de 120 días (${$(muerto.reduce((a, m) => a + m.valor, 0))} parados).`, grafica: f.sucursal ? null : { tipo: 'doughnut', titulo: 'Valor del inventario por sucursal', labels: porSuc.map(s => s.nombre), series: [{ label: 'Valor', data: porSuc.map(s => Math.round(s.valor)) }] }, sugerencias: ['¿Qué está bajo mínimo?', '¿Qué está parado?', 'Existencia de cemento gris'], acciones: [{ label: 'Ver existencias', tipo: 'ir', vista: 'inventario-existencias' }] }, fuente('existencias y catálogo', 'Días de inventario'));
  }
  function rPorPagar(q) { const c = M.cuentasPorPagar(); const sem = c.lista.filter(f => f.vence >= HOY && f.vence <= E.iso(E.addDays(hoy, 7))); const dup = M.duplicadasProveedor().filter(d => d.estados.includes('por pagar')); return Object.assign({ texto: `Cuentas por pagar: <b>${$(c.total)}</b> en ${c.lista.length} facturas. Esta semana vencen <b>${$(sem.reduce((a, f) => a + f.total, 0))}</b> (${sem.length} facturas); en 15 días, ${$(c.proximas15)}. Vencidas: ${$(c.vencidas)}.${dup.length ? ' <b>Ojo:</b> ' + dup.length + ' de las facturas por pagar son duplicadas (' + $(dup.reduce((a, d) => a + d.total, 0)) + '); cancélalas antes de programar el pago.' : ''}`, tabla: tabla(['Factura', 'Proveedor', 'Vence', 'Total', 'Estado'], c.lista.slice(0, 10).map(f => [f.id, E.nombreDe.prov(f.proveedor).split(',')[0], E.fechaCorta(f.vence), $$(f.total), f.estado + (f.duplicada ? ' · duplicada' : '')])), sugerencias: ['Muéstrame las duplicadas', '¿Cuánto tenemos en bancos?'], acciones: [{ label: 'Programar pagos', tipo: 'ir', vista: 'finanzas-pagos' }] }, fuente('facturas de proveedor')); }
  function rBancos(ctx) { if (!puede(ctx, 'bancos')) return candado('los saldos en bancos'); const saldo = db.bancos.reduce((a, b) => a + b.saldo, 0); const car = M.cartera(); const cxp = M.cuentasPorPagar(); const cobros15 = db.facturas.filter(f => f.estado === 'pendiente' && f.vence <= E.iso(E.addDays(hoy, 15))).reduce((a, f) => a + f.total, 0); return Object.assign({ texto: `Saldo en bancos: <b>${$(saldo)}</b> (${db.bancos.map(b => b.nombre.split(' ·')[0] + ' ' + $(b.saldo)).join(', ')}). En 15 días vencen cobros por ${$(cobros15)} y pagos por ${$(cxp.proximas15)}: flujo neto esperado <b>${$(cobros15 - cxp.proximas15)}</b> si los clientes pagan a tiempo. La cartera vencida (${$(car.totalVencido)}) es la palanca más rápida para mejorar la caja.`, grafica: { tipo: 'doughnut', titulo: 'Saldo por banco', labels: db.bancos.map(b => b.nombre), series: [{ label: 'Saldo', data: db.bancos.map(b => Math.round(b.saldo)) }] }, sugerencias: ['¿Quién me debe?', '¿Qué vence esta semana?'], acciones: [{ label: 'Ver Tesorería', tipo: 'ir', vista: 'finanzas-tesoreria' }] }, fuente('bancos, facturas y facturas de proveedor')); }
  function rPrecio(f) { const suc = f.sucursal ? [E.idx.suc[f.sucursal]] : db.sucursales; const series = suc.map(s => ({ s, pp: M.precioPromedio({ sucursal: s.id, linea: f.linea }).slice(-9) })); const frases = series.map(({ s, pp }) => { const a = pp[0], b = pp[pp.length - 1]; return s.nombre + ' ' + signo(b.indice / a.indice - 1); }); const baja = series.filter(({ pp }) => pp[pp.length - 1].indice / pp[0].indice - 1 < -0.015); return Object.assign({ texto: `Precio promedio realizado (deflactado contra la lista del día) en los últimos 9 meses: ${frases.join(', ')}. ${baja.length ? '<b>' + baja.map(b => b.s.nombre).join(' y ') + '</b> ' + (baja.length > 1 ? 'venden' : 'vende') + ' cada vez más barato: más descuento por el mismo producto. En Oriente eso coincide con la caída de venta; conviene revisar los descuentos autorizados por vendedor.' : 'Ninguna sucursal muestra una caída relevante de precio.'}`, grafica: { tipo: 'line', titulo: 'Índice de precio realizado (1.00 = lista)', labels: series[0].pp.map(p => E.mesLabel(p.mes)), series: series.map(({ s, pp }) => ({ label: s.nombre, data: pp.map(p => Math.round(p.indice * 1000) / 1000) })) }, sugerencias: ['¿Cómo va Oriente?', 'Descuentos por vendedor de Oriente'], acciones: [{ label: 'Abrir informe de ventas', tipo: 'ir', vista: 'informes', filtro: 'ventas' }] }, fuente('líneas de factura y catálogo', 'Precio promedio')); }
  function rVendedores(f, per, q) { const k = per && per.ym ? per.ym : E.mesActual; const rango = per && per.tipo !== 'mes' ? { desde: per.desde, hasta: per.hasta } : { desde: E.rangoMes(k)[0], hasta: E.rangoMes(k)[1] }; if (f.vendedor) { const v = f.vendedor; const r = M.resumen(M.filtrarLineas(Object.assign({ vendedor: v.id }, rango))); const cl = db.clientes.filter(c => c.vendedor === v.id); const car = M.cartera({ vendedor: v.id }); const ina = M.clientesInactivos(60).filter(c => c.vendedor === v.id); return Object.assign({ texto: `${v.nombre} (${E.nombreDe.suc(v.sucursal)}): <b>${$(r.venta)}</b> en ${per ? per.etiqueta : E.mesLabel(k, true)} con ${r.facturas} facturas. Atiende ${cl.length} clientes; ${ina.length ? '<b>' + ina.length + ' dejaron de comprar</b> (' + ina.map(c => c.nombre.split(',')[0]).join(', ') + ')' : 'ninguno inactivo'}. Cartera vencida de sus clientes: ${$(car.totalVencido)}.`, sugerencias: ['Prepara el mensaje para ' + v.nombre.split(' ')[0], 'Ranking de vendedores'], acciones: [{ label: 'Ver vendedor', tipo: 'ir', vista: 'ventas-vendedores', filtro: v.id }] }, fuente('facturas, clientes y pagos')); } const rows = M.por('vendedor', Object.assign({ sucursal: f.sucursal }, rango)); const lista = esPeor(q) ? rows.slice().reverse() : rows; return Object.assign({ texto: `Vendedores en ${per ? per.etiqueta : E.mesLabel(k, true)}${f.sucursal ? ', ' + nombreSuc(f.sucursal) : ''}: ${esPeor(q) ? 'el más bajo' : 'el más alto'} es <b>${lista[0].nombre}</b> con ${$(lista[0].venta)} (${E.nombreDe.suc(E.idx.vend[lista[0].id].sucursal)}). La diferencia entre el primero y el último es de ${$(rows[0].venta - rows[rows.length - 1].venta)}.`, tabla: tabla(['#', 'Vendedor', 'Sucursal', 'Venta neta', 'Facturas', 'Ticket'], lista.slice(0, topN(q) > 5 ? topN(q) : 12).map((r, i) => [i + 1, r.nombre, E.nombreDe.suc(E.idx.vend[r.id].sucursal), $$(r.venta), r.facturas, $$(r.ticket)])), grafica: { tipo: 'bar', titulo: 'Venta neta por vendedor', labels: rows.map(r => r.nombre.split(' ')[0]), series: [{ label: 'Venta', data: rows.map(r => Math.round(r.venta)) }] }, sugerencias: ['¿Y su margen?', '¿Qué clientes tiene ' + rows[0].nombre.split(' ')[0] + '?'], acciones: [{ label: 'Ver vendedores', tipo: 'ir', vista: 'ventas-vendedores' }] }, fuente('facturas y líneas de factura', 'Venta neta')); }
  function rCliente(f, per) { const c = f.cliente; const r12 = M.resumen(M.filtrarLineas({ cliente: c.id, desde: E.iso(E.addDays(hoy, -365)) })); const rPrev = M.resumen(M.filtrarLineas({ cliente: c.id, desde: E.iso(E.addDays(hoy, -730)), hasta: E.iso(E.addDays(hoy, -366)) })); const fs = db.facturas.filter(x => x.cliente === c.id).sort((a, b) => a.fecha < b.fecha ? 1 : -1); const car = M.cartera({ cliente: c.id }); const top = M.por('linea', { cliente: c.id, desde: E.iso(E.addDays(hoy, -365)) }); const meses = M.porMes({ cliente: c.id, desde: E.iso(E.addDays(hoy, -365)) }); return Object.assign({ texto: `${c.nombre}: cliente ${c.tamano} de ${E.nombreDe.suc(c.sucursal)}, atendido por ${E.nombreDe.vend(c.vendedor)}. En 12 meses compró <b>${$(r12.venta)}</b> (${signo(rPrev.venta ? r12.venta / rPrev.venta - 1 : null)} contra los 12 anteriores) en ${r12.facturas} facturas; lo que más compra es ${top.slice(0, 2).map(t => t.nombre).join(' y ')}. Última compra: ${fs.length ? E.fechaLarga(fs[0].fecha) + ' (' + E.diasEntre(fs[0].fecha, HOY) + ' días)' : '—'}. ${car.totalVencido ? '<b>Debe ' + $(car.totalVencido) + ' vencidos</b>; ' : 'Sin saldo vencido; '}crédito a ${c.credito} días, límite ${$(c.limite)}.`, grafica: { tipo: 'bar', titulo: 'Compras por mes', labels: meses.map(m => E.mesLabel(m.mes)), series: [{ label: 'Venta neta', data: meses.map(m => Math.round(m.venta)) }] }, sugerencias: ['¿Qué le vendimos este mes?', car.totalVencido ? 'Redacta el recordatorio de pago' : '¿Qué productos ya no nos compra?'], acciones: [{ label: 'Ver cliente', tipo: 'ir', vista: 'ventas-clientes', filtro: c.id }] }, fuente('facturas, líneas y pagos')); }
  function rProducto(f, per) { const p = f.producto; const rango = per ? { desde: per.desde, hasta: per.hasta } : { desde: E.iso(E.addDays(hoy, -365)), hasta: HOY }; const r = M.resumen(M.filtrarLineas(Object.assign({ producto: p.id, sucursal: f.sucursal }, rango))); const porS = M.por('sucursal', Object.assign({ producto: p.id }, rango)); const ex = db.existencias.filter(e => e.producto === p.id).reduce((a, e) => a + e.existencia, 0); const neg = M.margenNegativo({ producto: p.id }); return Object.assign({ texto: `${p.nombre} en ${per ? per.etiqueta : 'los últimos 12 meses'}${f.sucursal ? ', ' + nombreSuc(f.sucursal) : ''}: <b>${E.num.format(r.unidades)} ${p.unidad}</b> por <b>${$(r.venta)}</b>, margen ${P(r.margenPct)}. ${porS.length ? 'Donde más se vende: ' + porS[0].nombre + ' (' + $(porS[0].venta) + ').' : ''} Existencia total ${E.num.format(ex)} ${p.unidad}; proveedor ${E.nombreDe.prov(p.proveedor).split(',')[0]}.${neg.length ? ' <b>Se está vendiendo por debajo del costo en ' + neg.map(n => n.sucursalNombre).join(' y ') + '</b> (precio de lista sin actualizar tras el aumento del proveedor).' : ''}`, tabla: porS.length ? tabla(['Sucursal', 'Unidades', 'Venta neta', '% margen'], porS.map(s => [s.nombre, E.num.format(s.unidades), $$(s.venta), P(s.margenPct)])) : null, sugerencias: ['¿Cuánto tenemos en existencia?', neg.length ? 'Actualiza el precio de ' + p.nombre.split(' ')[0].toLowerCase() : '¿Quién lo compra más?'], acciones: [{ label: 'Ver producto', tipo: 'ir', vista: 'inventario-productos', filtro: p.id }].concat(neg.length ? [{ label: 'Actualizar precio', tipo: 'precio', producto: p.id }] : []) }, fuente('líneas de factura, existencias y catálogo')); }
  function rPipeline() { const p = M.pipeline(); const ab = db.cotizaciones.filter(c => c.estado === 'abierta').sort((a, b) => b.subtotal - a.subtotal); const ped = db.pedidos.filter(x => x.estado === 'por surtir' || x.estado === 'parcial'); const atras = ped.filter(x => x.entrega < HOY); return Object.assign({ texto: `Hay <b>${p.abiertas} cotizaciones abiertas</b> por ${$(p.montoAbierto)} y la tasa de cierre de los últimos 75 días es ${P(p.cierre, 0)}. Pedidos por surtir: <b>${ped.length}</b> (${$(ped.reduce((a, x) => a + x.subtotal, 0))})${atras.length ? ', <b>' + atras.length + ' ya pasaron su fecha de entrega</b>' : ''}. La cotización más grande abierta es de ${E.nombreDe.cli(ab[0].cliente).split(',')[0]} por ${$(ab[0].subtotal)} (vence ${E.fechaCorta(ab[0].vigencia)}).`, tabla: tabla(['Cotización', 'Cliente', 'Vendedor', 'Vigencia', 'Subtotal'], ab.slice(0, 6).map(c => [c.id, E.nombreDe.cli(c.cliente).split(',')[0], E.nombreDe.vend(c.vendedor), E.fechaCorta(c.vigencia), $$(c.subtotal)])), sugerencias: ['¿Qué pedidos van atrasados?', 'Recuérdame dar seguimiento a la cotización más grande'], acciones: [{ label: 'Ver pedidos y cotizaciones', tipo: 'ir', vista: 'ventas-pedidos' }] }, fuente('cotizaciones y pedidos')); }
  function rHallazgos(ctx) { const h = M.hallazgos().filter(x => puede(ctx, x.tipo === 'margen' ? 'margen' : 'x')); return Object.assign({ texto: `Revisé todo el ERP esta mañana. Esto es lo que me preocupa, en orden:` + li(h.map(x => `<b>${x.titulo}.</b> ${x.detalle}`)) + 'Dime por cuál empezamos y te preparo la acción.', hallazgos: h, sugerencias: ['Muéstrame las duplicadas', '¿Qué clientes dejaron de comprar?', '¿Qué está bajo costo?'], acciones: h.slice(0, 4).map(x => ({ label: x.accion, tipo: 'ir', vista: x.vista, filtro: x.filtro })) }, fuente('todas las tablas del ERP')); }
  function rMensaje(q, f, ctx) {
    const ina = M.clientesInactivos(60).filter(c => c.tamano !== 'chico');
    if (/vendedor|oriente/.test(q) && ina.length) { const v = E.idx.vend[ina[0].vendedor]; const cuerpo = `Hola ${v.nombre.split(' ')[0]}, buenos días.\n\nRevisando las cuentas de ${E.nombreDe.suc(v.sucursal)} veo que tres clientes que compraban seguido no han facturado desde finales de junio:\n${ina.filter(c => c.vendedor === v.id).map(c => `• ${c.nombre.split(',')[0]}: última compra ${E.fechaLarga(c.ultima)}, compraba ${E.corto(c.venta12)} al año.`).join('\n')}\n\nEntre los tres son ${E.corto(ina.filter(c => c.vendedor === v.id).reduce((a, c) => a + c.venta12, 0))} al año. Te pido que los contactes esta semana, entiendas si se fueron con otro proveedor o tienen algún problema de servicio o precio, y me digas qué encontraste el viernes.\n\nGracias.`; return Object.assign({ texto: 'Listo, aquí está el borrador para ' + v.nombre + '. Lo dejo con los datos exactos del ERP; ajusta el tono si quieres y lo marco como enviado para darle seguimiento el viernes.', borrador: { para: v.nombre, asunto: 'Clientes de ' + E.nombreDe.suc(v.sucursal) + ' sin compras desde junio', cuerpo }, sugerencias: ['Márcalo como enviado y recuérdamelo el viernes', '¿Cuánto vendía Oriente el año pasado?'], acciones: [{ label: 'Marcar como enviado y dar seguimiento', tipo: 'encargo', texto: 'Seguimiento con ' + v.nombre.split(' ')[0] + ' el viernes: clientes de Oriente sin compras desde junio', estado: 'en curso' }, { label: 'Copiar borrador', tipo: 'copiar' }] }, fuente('facturas y clientes')); }
    if (/proveedor|aumento|subio/.test(q) || f.proveedor) { const a = M.aumentosProveedor()[0]; const v = f.proveedor || (a && E.idx.prov[a.proveedor]); if (!v) return sinDato('No encuentro un proveedor con aumento reciente.'); const cuerpo = `Estimado ${v.contacto}:\n\nEn ${EMP()} revisamos las compras del último trimestre y encontramos que los precios de ${v.nombre.split(',')[0]} subieron ${P(a ? a.variacion : 0, 0)} respecto al trimestre anterior, sin que tengamos registro de una renegociación o aviso formal.\n\nEn ese periodo les compramos ${E.corto(a ? a.compras90 : 0)}. Les pedimos una explicación del ajuste y una propuesta de precio para el siguiente trimestre; de lo contrario tendremos que cotizar con otros proveedores de la línea.\n\nQuedo atento.\n\n${ctx.usuario || 'Dirección'} · ${EMP()}`; return Object.assign({ texto: 'Este es el borrador para ' + v.nombre.split(',')[0] + ', con el porcentaje y el monto que salen del ERP.', borrador: { para: v.contacto + ' · ' + v.nombre.split(',')[0], asunto: 'Ajuste de precios sin aviso · solicitud de revisión', cuerpo }, sugerencias: ['Márcalo como enviado', '¿Qué otro proveedor vende acero?'], acciones: [{ label: 'Marcar como enviado y dar seguimiento', tipo: 'encargo', texto: 'Seguimiento a la respuesta de ' + v.nombre.split(',')[0] + ' por el aumento de ' + P(a ? a.variacion : 0, 0), estado: 'en curso' }, { label: 'Copiar borrador', tipo: 'copiar' }] }, fuente('órdenes de compra y proveedores')); }
    if (/compras|duplicad/.test(q)) { const d = M.duplicadasProveedor(); const cuerpo = `Equipo de Compras:\n\nEl asistente detectó ${d.length} facturas de proveedor capturadas dos veces (mismo proveedor, mismo folio, mismo total) por ${E.corto(d.reduce((a, x) => a + x.total, 0))}:\n${d.slice(0, 14).map(x => `• ${x.nombre.split(',')[0]} · folio ${x.folioProv} · ${E.money0(x.total)} · ${x.pagadaDosVeces ? 'PAGADA DOS VECES' : x.estados.join('/')}`).join('\n')}\n\nFavor de cancelar las que siguen por pagar hoy mismo y gestionar la nota de crédito de las ya pagadas. Confírmenme por esta vía cuando esté hecho.`; return Object.assign({ texto: 'Borrador para Compras con la lista exacta de las duplicadas.', borrador: { para: 'Compras', asunto: 'Facturas de proveedor duplicadas · acción hoy', cuerpo }, sugerencias: ['Márcalo como enviado'], acciones: [{ label: 'Marcar como enviado y dar seguimiento', tipo: 'encargo', texto: 'Confirmación de Compras: cancelar duplicadas y notas de crédito', estado: 'en curso' }, { label: 'Copiar borrador', tipo: 'copiar' }] }, fuente('facturas de proveedor')); }
    // cobranza (cliente específico o vencidos)
    const car = M.cartera(f.cliente ? { cliente: f.cliente.id } : {}); const obj = f.cliente ? car.porCliente.filter(x => x.cliente === f.cliente.id) : car.porCliente.filter(x => x.maxDias > (/90/.test(q) ? 90 : /60/.test(q) ? 60 : /30/.test(q) ? 30 : 0)).slice(0, 5);
    if (!obj.length) return sinDato('No hay clientes con saldo vencido en ese criterio.');
    const c = obj[0]; const facs = car.vencidas.filter(v => v.cliente === c.cliente); const cuerpo = `Estimado cliente ${c.nombre.split(',')[0]}:\n\nLe recordamos que a la fecha tiene un saldo vencido de ${E.money0(c.saldo)} con ${EMP()}, correspondiente a ${facs.length > 1 ? 'las facturas' : 'la factura'}:\n${facs.map(v => `• ${v.id} del ${E.fechaLarga(v.fecha)}, vencida el ${E.fechaLarga(v.vence)} (${v.dias} días): ${E.money0(v.saldo)}`).join('\n')}\n\nLe agradeceremos programar el pago esta semana o indicarnos la fecha en que lo realizará. Si ya lo hizo, favor de enviarnos el comprobante.\n\nAtentamente,\nCobranza · ${EMP()}`; return Object.assign({ texto: `Preparé el recordatorio para <b>${c.nombre.split(',')[0]}</b> (${$(c.saldo)} vencidos, ${c.maxDias} días)${obj.length > 1 ? ' y tengo listos otros ' + (obj.length - 1) + ' con el mismo formato: ' + obj.slice(1).map(x => x.nombre.split(',')[0]).join(', ') : ''}. Van con los folios y fechas exactos.`, borrador: { para: c.nombre.split(',')[0] + ' · ' + (E.idx.cli[c.cliente] || {}).correo, asunto: 'Recordatorio de pago · saldo vencido ' + E.money0(c.saldo), cuerpo }, sugerencias: ['Márcalo como enviado', '¿Cómo va la cobranza?'], acciones: [{ label: 'Marcar como enviado y dar seguimiento', tipo: 'encargo', texto: 'Seguimiento de cobranza a ' + c.nombre.split(',')[0] + ' (' + E.corto(c.saldo) + ')', estado: 'en curso' }, { label: 'Copiar borrador', tipo: 'copiar' }, { label: 'Ver en Cobranza', tipo: 'ir', vista: 'finanzas-cobranza', filtro: c.cliente }] }, fuente('facturas y pagos'));
  }
  function rEncargo(q, original) { const cuando = /viernes/.test(q) ? 'el viernes' : /lunes/.test(q) ? 'el lunes' : /manana/.test(q) ? 'mañana' : /semana/.test(q) ? 'la próxima semana' : null; const texto = original.replace(/^(recuerdame|recuérdame|vigila|avisame|avísame|dale seguimiento a|pendiente:?)\s*/i, '').trim(); const enc = E.agregar('encargos', { id: 'k' + Date.now(), fecha: HOY, texto: cap(texto || original), estado: /vigila|avisa/.test(q) ? 'vigilando' : 'pendiente', tipo: /vigila|avisa/.test(q) ? 'vigilancia' : 'recordatorio', seguimiento: cuando ? 'Te aviso ' + cuando : 'Sin fecha; te lo recuerdo en el resumen de la mañana' }); return Object.assign({ texto: `Anotado: <b>${enc.texto}</b>. ${enc.seguimiento}. Lo verás en tus encargos y te lo traigo en el resumen de la mañana hasta que lo cierres.`, sugerencias: ['Muéstrame mis encargos', '¿Qué más me preocupa?'], acciones: [{ label: 'Ver encargos', tipo: 'ir', vista: 'asistente', filtro: 'encargos' }] }, fuente('encargos del asistente')); }
  function rEncargos() { const e = db.encargos.slice().reverse(); return Object.assign({ texto: e.length ? `Tienes ${e.length} encargo${e.length > 1 ? 's' : ''}:` + li(e.map(x => `<b>${x.texto}</b> · ${x.estado} · ${x.seguimiento || ''}`)) : 'No tienes encargos pendientes.', sugerencias: ['Recuérdame revisar la cartera el lunes', '¿Qué me preocupa hoy?'], acciones: [{ label: 'Ver encargos', tipo: 'ir', vista: 'asistente', filtro: 'encargos' }] }, fuente('encargos del asistente')); }
  function rDefiniciones(q) { const d = db.definiciones.find(x => norm(x.nombre).split(' ').some(t => t.length > 4 && q.includes(t))); return Object.assign({ texto: d ? `<b>${d.nombre}</b>: ${d.formula} Es la misma definición que usa Power BI, así mis números y los del informe coinciden.` : 'Uso las mismas definiciones que Power BI:' + li(db.definiciones.map(x => `<b>${x.nombre}</b>: ${x.formula}`)), sugerencias: ['¿Cómo cerró agosto?', '¿Cómo calculas el margen?'], acciones: [{ label: 'Ver definiciones', tipo: 'ir', vista: 'config', filtro: 'definiciones' }] }, fuente('definiciones del negocio (Power BI)')); }
  function rPersonal(ctx) { if (!puede(ctx, 'nomina')) return candado('la nómina'); const porS = db.sucursales.map(s => ({ n: s.nombre, c: db.personal.filter(e => e.sucursal === s.id).length })); return Object.assign({ texto: `${db.personal.length} personas en nómina: ${porS.map(x => x.n + ' ' + x.c).join(', ')}. Nómina mensual ${$(db.personal.reduce((a, e) => a + e.sueldo, 0))}. ${db.vendedores.length} vendedores.`, sugerencias: ['Ranking de vendedores'], acciones: [{ label: 'Ver personal', tipo: 'ir', vista: 'personal' }] }, fuente('personal')); }
  function rAyuda() { return { texto: `Soy Vera, el asistente del ERP. Pregúntame en lenguaje normal y te contesto con los datos del sistema, nunca con estimaciones. Puedo:` + li(['<b>Responder</b>: «¿Cómo cerró agosto?», «¿Cuánto vendió Norte este año?», «Existencia de cemento gris».', '<b>Analizar</b>: «Ventas por sucursal contra el año pasado», «¿Por qué bajó el margen?», «Precio promedio por sucursal».', '<b>Criticar</b>: «¿Qué productos se venden bajo costo?», «¿Qué no cuadra en compras?».', '<b>Encontrar</b>: «¿Qué me preocupa hoy?», «Facturas duplicadas», «¿Qué clientes dejaron de comprar?».', '<b>Resolver</b>: «Prepara el mensaje para el vendedor de Oriente», «Redacta el recordatorio de pago», «Recuérdame revisar la cartera el lunes».']) + 'Cada respuesta trae su fuente y la definición que usé (la misma que Power BI).', sugerencias: ['¿Qué me preocupa hoy?', '¿Cómo cerró agosto?', 'Revisa las compras del trimestre'], acciones: [], fuente: 'Vera' }; }
  function candado(que) { return { texto: `Ese dato está reservado: <b>${que}</b> solo lo ve dirección y finanzas. El candado vive en el servidor, no en la pantalla, así que no puedo mostrarlo desde este acceso. Puedo ayudarte con ventas, clientes, inventario y pedidos.`, sugerencias: ['¿Cómo va el mes?', '¿Qué está bajo mínimo?'], acciones: [], fuente: 'permisos por rol', candado: true }; }
  function sinDato(msg) { return { texto: (msg || 'Ese dato no está en el ERP.') + ' No lo estimo ni lo invento: si lo necesitas, dime de dónde debería salir y lo conectamos.', sugerencias: ['¿Qué puedes hacer?', '¿Qué me preocupa hoy?'], acciones: [], fuente: 'sin fuente en el ERP' }; }
  function EMP() { return E.db.empresa.corto; }
  function puede(ctx, que) { const rol = (ctx && ctx.rol) || 'direccion'; if (['margen', 'bancos', 'nomina'].includes(que)) return rol === 'direccion' || rol === 'finanzas'; return true; }

  // ---------- enrutador ----------
  function responder(original, ctx) {
    ctx = ctx || {}; const q = norm(original); const t0 = performance.now();
    const f = { sucursal: sucursal(q) || ctx.sucursal || null, linea: linea(q), producto: null, cliente: null, vendedor: null, proveedor: null };
    const corta = q.split(' ').length <= 5 && ctx.memoria && ctx.memoria.original && /^(y |en |por |del |de |el |la |los |las |ahora )/.test(q);
    const per = periodo(q) || ((corta || /^y\b/.test(q) || q.split(' ').length <= 4) && ctx.memoria && ctx.memoria.per) || null; const dim = dimension(q);
    let r;
    if (/^(hola|buen|que puedes|que sabes|ayuda|como funcionas|quien eres)/.test(q)) r = rAyuda();
    else if (/duplicad/.test(q)) r = rDuplicadas();
    else if (/me preocupa|que esta mal|hallazgo|alerta|problema|revisa todo|resumen del dia|resumen de la manana|que hay de nuevo|novedades/.test(q)) r = rHallazgos(ctx);
    else if (/encargos|mis pendientes|que tengo pendiente/.test(q)) r = rEncargos();
    else if (/^(recuerdame|recuérdame|vigila|avisame|avísame|dale seguimiento|pendiente)/.test(q) || /recuerdame|recuerdamelo|marcalo como enviado|marca como enviado/.test(q)) r = rEncargo(q, original);
    else if (/redacta|prepara (el|un|los|la) (mensaje|correo|recordatorio|borrador)|escribe (el|un) (mensaje|correo)|borrador|recordatorio de pago|mensaje para/.test(q)) { f.cliente = cliente(q); f.proveedor = proveedor(q); r = rMensaje(q, f, ctx); }
    else if (/como calculas|definicion|que es (la |el )?(venta neta|margen|cartera|dias de inventario)|power bi/.test(q)) r = rDefiniciones(q);
    else if (/proveedor|aumento|subio (sus )?precios|sub(ió|io) /.test(q) && !/cliente/.test(q)) { f.proveedor = proveedor(q); if (f.proveedor || /aumento|subio|revisa|proveedores/.test(q)) r = rCompras(f, per, q); }
    else if (/compras|orden(es)? de compra|comprado|comprar a/.test(q) && !/por pagar/.test(q)) r = rCompras(f, per, q);
    else if (/por pagar|cuentas por pagar|pagar a proveedores|pagos programados|que vence|vencen? (esta|la) semana/.test(q) && !/cobr|cliente/.test(q)) r = rPorPagar(q);
    else if (/banco|saldo en|flujo|tesoreria|caja|efectivo disponible|liquidez/.test(q)) r = rBancos(ctx);
    else if (/dejaron de comprar|dejo de comprar|inactiv|no compran|sin comprar|no han comprado|perdimos|ya no compran/.test(q)) r = rInactivos(f);
    else if (/vencid|cobranza|cartera|me debe|deben|adeud|moros|cobrar|quien debe/.test(q)) { f.cliente = cliente(q); if (f.cliente) f.cliente = f.cliente.id; r = rCartera(f, q); }
    else if (/inventario|existencia|stock|almacen|bajo minimo|muerto|sin rotacion|reordenar|parado/.test(q)) { f.producto = producto(q); r = rInventario(f, q); }
    else if (/precio promedio|precios (a la baja|bajan|caen)|descuento|indice de precio|vende(n)? mas barato/.test(q)) r = rPrecio(f);
    else if (/margen|utilidad|ganancia|rentab|bajo costo|debajo del costo|por debajo/.test(q)) r = rMargen(f, per, dim, q, ctx);
    else if (/pedido|cotizacion|pipeline|por surtir|tasa de cierre|embudo/.test(q)) r = rPipeline();
    else if (/vendedor|equipo de ventas|quien vendio|ranking/.test(q)) { f.vendedor = vendedor(q); r = rVendedores(f, per, q); }
    else if (/empleados|personal|nomina|cuantos trabajan|plantilla/.test(q)) r = rPersonal(ctx);
    else {
      f.cliente = cliente(q); f.producto = producto(q); f.vendedor = vendedor(q);
      if (f.cliente && !/producto/.test(q)) r = rCliente(f, per);
      else if (f.producto) r = rProducto(f, per);
      else if (f.vendedor) r = rVendedores(f, per, q);
      else if (/vent|vend|cerro|como va|como vamos|factur|ingreso|cuanto|total|compar|crec|baj|resultado|top|mejores|peores|clientes|por sucursal|por linea/.test(q)) r = rComparativo(f, per, dim || (/clientes|top|mejores|peores/.test(q) ? (/cliente/.test(q) ? 'cliente' : /producto/.test(q) ? 'producto' : dim) : dim), q);
      else if (corta) return responder(ctx.memoria.original + ' ' + original, Object.assign({}, ctx, { memoria: { per: ctx.memoria.per } }));
      else r = sinDato('No encuentro eso en el ERP.');
    }
    if (!r) r = sinDato();
    const ms = Math.round(performance.now() - t0) + 1800 + Math.round(Math.random() * 1600); // simula el tiempo del modelo
    const costo = Math.round((0.18 + (original.length + (r.texto || '').length) * 0.00035) * 100) / 100; // MXN estimado con precios de lista
    r.costo = costo; r.ms = ms; r.hora = ahora(); r.pregunta = original; r.per = per; r.ok = r.fuente !== 'sin fuente en el ERP';
    E.agregar('bitacora', { fecha: HOY + ' ' + ahora(), usuario: ctx.usuario || 'Dirección', pregunta: original, tablas: (r.fuente || '').replace('ERP · ', ''), costo, ms });
    return r;
  }
  const sugerenciasIniciales = (rol) => rol === 'ventas' ? ['¿Cómo va el mes en mi sucursal?', '¿Qué clientes dejaron de comprar?', 'Top 10 clientes de agosto', '¿Qué pedidos van atrasados?'] : rol === 'compras' ? ['Revisa las compras del trimestre', 'Facturas duplicadas', '¿Qué proveedor subió precios?', '¿Qué está bajo mínimo?'] : rol === 'almacen' ? ['¿Qué está bajo mínimo?', '¿Qué está parado en inventario?', 'Existencia de cemento gris', '¿Qué pedidos hay por surtir?'] : rol === 'finanzas' ? ['¿Quién me debe más de 60 días?', '¿Qué vence esta semana por pagar?', '¿Cuánto tenemos en bancos?', 'Redacta el recordatorio para los vencidos'] : ['¿Qué me preocupa hoy?', '¿Cómo cerró agosto?', 'Revisa las compras del trimestre', '¿Qué clientes dejaron de comprar?'];
  window.Vera = { nombre: 'Vera', responder, sugerenciasIniciales, norm };
})();
